




















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `SSPC_EORDER_DB`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=10.233.217.39; Initial Catalog=EOrder_SSPC_TEST; user id=user_bfp;password=**zapped**;packet size=4096`
//     Schema:                 ``
//     Include Views:          `False`



using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Service.Sync.DB
{

	public partial class SSPC_EORDER_DB : Database
	{
		public SSPC_EORDER_DB() 
			: base("SSPC_EORDER_DB")
		{
			CommonConstruct();
		}

		public SSPC_EORDER_DB(string connectionStringName) 
			: base(connectionStringName)
		{
			CommonConstruct();
		}
		
		partial void CommonConstruct();
		
		public interface IFactory
		{
            SSPC_EORDER_DB GetInstance();
		}
		
		public static IFactory Factory { get; set; }
        public static SSPC_EORDER_DB GetInstance()
        {
			if (_instance!=null)
				return _instance;
				
			if (Factory!=null)
				return Factory.GetInstance();
			else
				return new SSPC_EORDER_DB();
        }

		[ThreadStatic] static SSPC_EORDER_DB _instance;
		
		public override void OnBeginTransaction()
		{
			if (_instance==null)
				_instance=this;
		}
		
		public override void OnEndTransaction()
		{
			if (_instance==this)
				_instance=null;
		}
        

		public class Record<T> where T:new()
		{
			public static SSPC_EORDER_DB repo { get { return SSPC_EORDER_DB.GetInstance(); } }
			public bool IsNew() { return repo.IsNew(this); }
			public object Insert() { return repo.Insert(this); }

			public void Save() { repo.Save(this); }
			public int Update() { return repo.Update(this); }

			public int Update(IEnumerable<string> columns) { return repo.Update(this, columns); }
			public static int Update(string sql, params object[] args) { return repo.Update<T>(sql, args); }
			public static int Update(Sql sql) { return repo.Update<T>(sql); }
			public int Delete() { return repo.Delete(this); }
			public static int Delete(string sql, params object[] args) { return repo.Delete<T>(sql, args); }
			public static int Delete(Sql sql) { return repo.Delete<T>(sql); }
			public static int Delete(object primaryKey) { return repo.Delete<T>(primaryKey); }
			public static bool Exists(object primaryKey) { return repo.Exists<T>(primaryKey); }
			public static bool Exists(string sql, params object[] args) { return repo.Exists<T>(sql, args); }
			public static T SingleOrDefault(object primaryKey) { return repo.SingleOrDefault<T>(primaryKey); }
			public static T SingleOrDefault(string sql, params object[] args) { return repo.SingleOrDefault<T>(sql, args); }
			public static T SingleOrDefault(Sql sql) { return repo.SingleOrDefault<T>(sql); }
			public static T FirstOrDefault(string sql, params object[] args) { return repo.FirstOrDefault<T>(sql, args); }
			public static T FirstOrDefault(Sql sql) { return repo.FirstOrDefault<T>(sql); }
			public static T Single(object primaryKey) { return repo.Single<T>(primaryKey); }
			public static T Single(string sql, params object[] args) { return repo.Single<T>(sql, args); }
			public static T Single(Sql sql) { return repo.Single<T>(sql); }
			public static T First(string sql, params object[] args) { return repo.First<T>(sql, args); }
			public static T First(Sql sql) { return repo.First<T>(sql); }
			public static List<T> Fetch(string sql, params object[] args) { return repo.Fetch<T>(sql, args); }
			public static List<T> Fetch(Sql sql) { return repo.Fetch<T>(sql); }
			public static List<T> Fetch(long page, long itemsPerPage, string sql, params object[] args) { return repo.Fetch<T>(page, itemsPerPage, sql, args); }
			public static List<T> Fetch(long page, long itemsPerPage, Sql sql) { return repo.Fetch<T>(page, itemsPerPage, sql); }
			public static List<T> SkipTake(long skip, long take, string sql, params object[] args) { return repo.SkipTake<T>(skip, take, sql, args); }
			public static List<T> SkipTake(long skip, long take, Sql sql) { return repo.SkipTake<T>(skip, take, sql); }
			public static Page<T> Page(long page, long itemsPerPage, string sql, params object[] args) { return repo.Page<T>(page, itemsPerPage, sql, args); }
			public static Page<T> Page(long page, long itemsPerPage, Sql sql) { return repo.Page<T>(page, itemsPerPage, sql); }
			public static IEnumerable<T> Query(string sql, params object[] args) { return repo.Query<T>(sql, args); }
			public static IEnumerable<T> Query(Sql sql) { return repo.Query<T>(sql); }

		}

	}

	[TableName("dbo.__MigrationHistory")]



	[PrimaryKey("MigrationId", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class __MigrationHistory : SSPC_EORDER_DB.Record<__MigrationHistory>  
    {



		[Column] public string MigrationId { get; set; }





		[Column] public string ContextKey { get; set; }





		[Column] public byte[] Model { get; set; }





		[Column] public string ProductVersion { get; set; }



	}

    

	[TableName("dbo.Sheet1$")]




	[ExplicitColumns]

    public partial class Sheet1_ : SSPC_EORDER_DB.Record<Sheet1_>  
    {



		[Column] public string ID { get; set; }





		[Column] public double? VKORG { get; set; }





		[Column] public string VTWGE { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string MATNR { get; set; }





		[Column] public DateTime? DATBI { get; set; }





		[Column] public DateTime? DATAB { get; set; }





		[Column] public double? KBETR { get; set; }





		[Column] public string KONWA { get; set; }





		[Column] public double? KPEIN { get; set; }





		[Column] public string KMEIN { get; set; }





		[Column] public double? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public double? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public string F16 { get; set; }





		[Column] public DateTime? F17 { get; set; }





		[Column] public DateTime? F18 { get; set; }





		[Column] public string F19 { get; set; }



	}

    

	[TableName("dbo.T_ExcelCustomer20180614")]




	[ExplicitColumns]

    public partial class T_ExcelCustomer20180614 : SSPC_EORDER_DB.Record<T_ExcelCustomer20180614>  
    {



		[Column] public string IT { get; set; }





		[Column] public string F2 { get; set; }





		[Column] public string F3 { get; set; }





		[Column] public string F4 { get; set; }





		[Column] public string F5 { get; set; }





		[Column] public double? F6 { get; set; }





		[Column] public string F7 { get; set; }





		[Column] public string F8 { get; set; }





		[Column] public string F9 { get; set; }





		[Column] public string F10 { get; set; }





		[Column] public string check { get; set; }





		[Column] public string F12 { get; set; }





		[Column] public string F13 { get; set; }





		[Column] public string F14 { get; set; }





		[Column] public string F15 { get; set; }



	}

    

	[TableName("dbo.T_ExcelCustomer20180622")]




	[ExplicitColumns]

    public partial class T_ExcelCustomer20180622 : SSPC_EORDER_DB.Record<T_ExcelCustomer20180622>  
    {



		[Column] public string 经销商编号 { get; set; }





		[Column] public string 经销商名称 { get; set; }





		[Column] public string 经销商简称 { get; set; }





		[Column] public string 负责部门 { get; set; }





		[Column] public string 商业状态 { get; set; }





		[Column] public string 员工编号 { get; set; }





		[Column] public string 员工名称 { get; set; }





		[Column] public string 是否提供公章 { get; set; }





		[Column] public string 是否经销商提供签字 { get; set; }





		[Column] public string 是否商务提供签字 { get; set; }





		[Column] public string 广销部 { get; set; }





		[Column] public string 简称 { get; set; }





		[Column] public string 公章 { get; set; }





		[Column] public string 签字 { get; set; }





		[Column] public string 备注 { get; set; }



	}

    

	[TableName("dbo.T_ExcelUserCompany")]




	[ExplicitColumns]

    public partial class T_ExcelUserCompany : SSPC_EORDER_DB.Record<T_ExcelUserCompany>  
    {



		[Column] public string customercode { get; set; }





		[Column] public string customername { get; set; }





		[Column] public string username { get; set; }



	}

    

	[TableName("dbo.tb_SQL")]




	[ExplicitColumns]

    public partial class tb_SQL : SSPC_EORDER_DB.Record<tb_SQL>  
    {



		[Column] public string SQLID { get; set; }





		[Column] public string Statement { get; set; }





		[Column] public string Instruction { get; set; }





		[Column] public Guid? NewSqlID { get; set; }



	}

    

	[TableName("dbo.TBL_T_AllButton_Info")]




	[ExplicitColumns]

    public partial class TBL_T_AllButton_Info : SSPC_EORDER_DB.Record<TBL_T_AllButton_Info>  
    {



		[Column] public Guid ButtonID { get; set; }





		[Column] public string ButtonCode { get; set; }





		[Column] public string ButtonName { get; set; }





		[Column] public string IconCls { get; set; }





		[Column] public int? StandardFlag { get; set; }





		[Column] public int? IndexFlag { get; set; }





		[Column] public string CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? InnerButton { get; set; }





		[Column] public string Remark { get; set; }



	}

    

	[TableName("dbo.TBL_T_AllField_Info")]




	[ExplicitColumns]

    public partial class TBL_T_AllField_Info : SSPC_EORDER_DB.Record<TBL_T_AllField_Info>  
    {



		[Column] public Guid FieldID { get; set; }





		[Column] public Guid? TableID { get; set; }





		[Column] public string FieldName { get; set; }





		[Column] public string FieldDisplay { get; set; }





		[Column] public int? CharLength { get; set; }





		[Column] public int? AutoGenerate { get; set; }





		[Column] public int? DefaultSelect { get; set; }





		[Column] public int? IndexFlag { get; set; }





		[Column] public int? IsPrimaryKey { get; set; }





		[Column] public string GenerateFunc { get; set; }





		[Column] public string CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("dbo.TBL_T_AllTable_Info")]




	[ExplicitColumns]

    public partial class TBL_T_AllTable_Info : SSPC_EORDER_DB.Record<TBL_T_AllTable_Info>  
    {



		[Column] public Guid TableID { get; set; }





		[Column] public string TableName { get; set; }





		[Column] public string TableDescription { get; set; }





		[Column] public int? FuncID { get; set; }





		[Column] public int? PrimaryKeyType { get; set; }





		[Column] public int? TableType { get; set; }





		[Column] public string RefMainTable { get; set; }





		[Column] public string CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? GenerateFlag { get; set; }



	}

    

	[TableName("dbo.TBL_T_BaseInfo")]




	[ExplicitColumns]

    public partial class TBL_T_BaseInfo : SSPC_EORDER_DB.Record<TBL_T_BaseInfo>  
    {



		[Column] public int InfoID { get; set; }





		[Column] public string InfoValue { get; set; }





		[Column] public string InfoCode { get; set; }





		[Column] public int? TypeID { get; set; }





		[Column] public string TypeValue { get; set; }





		[Column] public int? IndexFlag { get; set; }





		[Column] public string Remark { get; set; }



	}

    

	[TableName("dbo.TBL_T_DataSql")]



	[PrimaryKey("SqlID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class TBL_T_DataSql : SSPC_EORDER_DB.Record<TBL_T_DataSql>  
    {



		[Column] public Guid SqlID { get; set; }





		[Column] public string SqlContent { get; set; }





		[Column] public string Description { get; set; }





		[Column] public int? BaseType { get; set; }





		[Column] public string Remark { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("dbo.TBL_T_Func_Table")]




	[ExplicitColumns]

    public partial class TBL_T_Func_Table : SSPC_EORDER_DB.Record<TBL_T_Func_Table>  
    {



		[Column] public Guid SerialID { get; set; }





		[Column] public int? FuncID { get; set; }





		[Column] public Guid? TableID { get; set; }



	}

    

	[TableName("dbo.TBL_T_Func_Template")]




	[ExplicitColumns]

    public partial class TBL_T_Func_Template : SSPC_EORDER_DB.Record<TBL_T_Func_Template>  
    {



		[Column] public int? FuncID { get; set; }





		[Column] public string FuncType { get; set; }





		[Column] public Guid? TemplateMainID { get; set; }



	}

    

	[TableName("dbo.TBL_T_MainTemplate")]




	[ExplicitColumns]

    public partial class TBL_T_MainTemplate : SSPC_EORDER_DB.Record<TBL_T_MainTemplate>  
    {



		[Column] public Guid TemplateMainID { get; set; }





		[Column] public string TemplateMainCode { get; set; }





		[Column] public string TemplateName { get; set; }





		[Column] public int? TemplateType { get; set; }





		[Column] public Guid? TemplateViewID { get; set; }





		[Column] public int? Creater { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string TemplateVersion { get; set; }





		[Column] public int? StatusFlag { get; set; }





		[Column] public string Width { get; set; }





		[Column] public string Height { get; set; }





		[Column] public string CreateUser { get; set; }





		[Column] public string UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("dbo.TBL_T_ProcedureBackup")]




	[ExplicitColumns]

    public partial class TBL_T_ProcedureBackup : SSPC_EORDER_DB.Record<TBL_T_ProcedureBackup>  
    {



		[Column] public Guid BackupID { get; set; }





		[Column] public string PorcedureName { get; set; }





		[Column] public DateTime? BackupTime { get; set; }





		[Column] public string PorcedureText { get; set; }



	}

    

	[TableName("dbo.TBL_T_SubTemplate")]




	[ExplicitColumns]

    public partial class TBL_T_SubTemplate : SSPC_EORDER_DB.Record<TBL_T_SubTemplate>  
    {



		[Column] public Guid TemplateSubID { get; set; }





		[Column] public string TemplateSubCode { get; set; }





		[Column] public Guid? TemplateMainID { get; set; }





		[Column] public Guid? ViewPartID { get; set; }





		[Column] public string PartFlag { get; set; }





		[Column] public Guid? TableID { get; set; }





		[Column] public string Title { get; set; }





		[Column] public string Description { get; set; }





		[Column] public int? IndexFlag { get; set; }





		[Column] public string Region { get; set; }





		[Column] public string IconCls { get; set; }





		[Column] public int? Border { get; set; }





		[Column] public string Height { get; set; }





		[Column] public string Width { get; set; }





		[Column] public int? ColumnsNum { get; set; }





		[Column] public int? WithPaging { get; set; }





		[Column] public int? GridType { get; set; }





		[Column] public string GroupField { get; set; }





		[Column] public string OrderBy { get; set; }





		[Column] public int? ShowTitle { get; set; }





		[Column] public int? HasSelectColumn { get; set; }





		[Column] public string SelectProcName { get; set; }





		[Column] public string InsertProcName { get; set; }





		[Column] public string UpdateProcName { get; set; }





		[Column] public string DeleteProcName { get; set; }





		[Column] public string ForeignKeySelect { get; set; }





		[Column] public string CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public string InsertCommonProc { get; set; }





		[Column] public string UpdateCommonProc { get; set; }





		[Column] public string DeleteCommonProc { get; set; }





		[Column] public string OrderType { get; set; }





		[Column] public int? GridForceFit { get; set; }



	}

    

	[TableName("dbo.TBL_T_Template_TreeAttritbute")]




	[ExplicitColumns]

    public partial class TBL_T_Template_TreeAttritbute : SSPC_EORDER_DB.Record<TBL_T_Template_TreeAttritbute>  
    {



		[Column] public Guid TemplateSubID { get; set; }





		[Column] public string NodeID { get; set; }





		[Column] public string NodeText { get; set; }





		[Column] public string NodeParent { get; set; }





		[Column] public string NodeCode { get; set; }





		[Column] public string CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("dbo.TBL_T_TemplateButton")]




	[ExplicitColumns]

    public partial class TBL_T_TemplateButton : SSPC_EORDER_DB.Record<TBL_T_TemplateButton>  
    {



		[Column] public Guid TemplateButtonID { get; set; }





		[Column] public Guid? TemplateSubID { get; set; }





		[Column] public Guid? ButtonID { get; set; }





		[Column] public int? IndexFlag { get; set; }





		[Column] public int? InnerButton { get; set; }





		[Column] public string ButtonCode { get; set; }





		[Column] public string IconCls { get; set; }





		[Column] public string Remark { get; set; }





		[Column] public string ButtonName { get; set; }





		[Column] public string CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public string DetailTemplate { get; set; }



	}

    

	[TableName("dbo.TBL_T_TemplateField")]




	[ExplicitColumns]

    public partial class TBL_T_TemplateField : SSPC_EORDER_DB.Record<TBL_T_TemplateField>  
    {



		[Column] public Guid TemplateFieldID { get; set; }





		[Column] public Guid? TemplateSubID { get; set; }





		[Column] public Guid? FieldID { get; set; }





		[Column] public string FieldName { get; set; }





		[Column] public string FieldDisplay { get; set; }





		[Column] public int? IndexFlag { get; set; }





		[Column] public string ControlType { get; set; }





		[Column] public int? IsVisible { get; set; }





		[Column] public int? IsReadOnly { get; set; }





		[Column] public int? AllowBlank { get; set; }





		[Column] public string LinkUrl { get; set; }





		[Column] public string Width { get; set; }





		[Column] public string Align { get; set; }





		[Column] public string Format { get; set; }





		[Column] public string SQLID { get; set; }





		[Column("Query")] public string _Query { get; set; }





		[Column] public string Remark { get; set; }





		[Column] public int? Locked { get; set; }





		[Column] public int? IsKey { get; set; }





		[Column] public string ConditionOperate { get; set; }





		[Column] public string FormatType { get; set; }





		[Column] public string CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? IsDisabled { get; set; }





		[Column] public int? Height { get; set; }





		[Column] public string Regex { get; set; }





		[Column] public string RegexText { get; set; }



	}

    

	[TableName("dbo.TBL_T_TemplateView")]




	[ExplicitColumns]

    public partial class TBL_T_TemplateView : SSPC_EORDER_DB.Record<TBL_T_TemplateView>  
    {



		[Column] public Guid TemplateViewID { get; set; }





		[Column] public string ViewCode { get; set; }





		[Column] public string ViewName { get; set; }





		[Column] public string PicturePath { get; set; }





		[Column] public int? UnknownPanel { get; set; }





		[Column] public string Description { get; set; }





		[Column] public int? StopFlag { get; set; }





		[Column] public int? IndexFlag { get; set; }



	}

    

	[TableName("dbo.tbl_T_TemplateViewPart")]




	[ExplicitColumns]

    public partial class tbl_T_TemplateViewPart : SSPC_EORDER_DB.Record<tbl_T_TemplateViewPart>  
    {



		[Column] public Guid ViewPartID { get; set; }





		[Column] public Guid? TemplateViewID { get; set; }





		[Column] public string PartName { get; set; }





		[Column] public string PartFlag { get; set; }





		[Column] public int? IndexFlag { get; set; }





		[Column] public int? AsCondition { get; set; }



	}

    

	[TableName("user_bfp.mstjibenleixing")]



	[PrimaryKey("LeiXingID")]




	[ExplicitColumns]

    public partial class mstjibenleixing : SSPC_EORDER_DB.Record<mstjibenleixing>  
    {



		[Column] public int LeiXingID { get; set; }





		[Column] public string LeiXingNM { get; set; }





		[Column] public int? WeiHuFlag { get; set; }





		[Column] public int? CLASSFLAG { get; set; }





		[Column] public string CLASSEXPLAIN { get; set; }





		[Column] public int? suoyin { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.mstJiBenXinXi")]



	[PrimaryKey("BianHao")]




	[ExplicitColumns]

    public partial class mstJiBenXinXi : SSPC_EORDER_DB.Record<mstJiBenXinXi>  
    {



		[Column] public int BianHao { get; set; }





		[Column] public int LeiXingID { get; set; }





		[Column] public string ShuZhi { get; set; }





		[Column] public int? SuoYin { get; set; }





		[Column] public int? CengCi { get; set; }





		[Column] public string SAPBianMa { get; set; }





		[Column] public string SAPBianMa1 { get; set; }





		[Column] public string ShuXing { get; set; }





		[Column] public string COLOR { get; set; }





		[Column] public decimal? BalaPara { get; set; }





		[Column] public int? ProGPShow { get; set; }





		[Column] public string ParentNode { get; set; }





		[Column] public int? miskey { get; set; }





		[Column] public string TEMPLATEID { get; set; }





		[Column] public string DIARYTEMPLATE { get; set; }





		[Column] public int? templateflag { get; set; }





		[Column] public int? intAdminFlag { get; set; }





		[Column] public DateTime? updatetime { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }



	}

    

	[TableName("user_bfp.mstquyu")]



	[PrimaryKey("QuYuID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class mstquyu : SSPC_EORDER_DB.Record<mstquyu>  
    {



		[Column] public int QuYuID { get; set; }





		[Column] public string QuYuNM { get; set; }





		[Column] public string QuYuPath { get; set; }





		[Column] public int bFlag { get; set; }





		[Column] public string SuoXie { get; set; }





		[Column] public string ParentCode { get; set; }





		[Column] public int? lockDataFlag { get; set; }





		[Column] public DateTime? btBeginDate { get; set; }





		[Column] public DateTime? btEndDate { get; set; }





		[Column] public int? Creater { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? Updater { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.mstrenyuan")]



	[PrimaryKey("RenYuanID")]




	[ExplicitColumns]

    public partial class mstrenyuan : SSPC_EORDER_DB.Record<mstrenyuan>  
    {



		[Column] public int RenYuanID { get; set; }





		[Column] public string LoginID { get; set; }





		[Column] public string ADName { get; set; }





		[Column] public string LoginPW { get; set; }





		[Column] public int? ShiFouTingYon { get; set; }





		[Column] public string RenYuanBH { get; set; }





		[Column] public string Sap_code { get; set; }





		[Column] public string RenYuanNM { get; set; }





		[Column] public string western_name { get; set; }





		[Column] public int QuYuID { get; set; }





		[Column] public string YiDongDianHua { get; set; }





		[Column] public string Email { get; set; }





		[Column] public string ZhiWu { get; set; }





		[Column] public string Address { get; set; }





		[Column] public int? ShiFouZaiZhi { get; set; }





		[Column] public string BanGongShiChuanZhen { get; set; }





		[Column] public int? SuoShuBuMen { get; set; }





		[Column] public string BeiZhu { get; set; }





		[Column] public int? ErrorTime { get; set; }





		[Column] public int? InitPWD { get; set; }





		[Column] public int? InitDownload { get; set; }





		[Column] public string Mail { get; set; }





		[Column] public string ChengHu { get; set; }





		[Column] public int? ChaKanDengJi { get; set; }





		[Column] public int? IsShenPiRen { get; set; }





		[Column] public int? LevelNO { get; set; }





		[Column] public string mobilePWD { get; set; }





		[Column] public DateTime? mobilePWDCreatedTime { get; set; }





		[Column] public int? UseMPW { get; set; }





		[Column] public int? XUELI { get; set; }





		[Column] public int? ManagerId { get; set; }





		[Column] public int? intZhiWu { get; set; }





		[Column] public int? country { get; set; }





		[Column] public string MD5Password { get; set; }





		[Column] public string nvPingYin { get; set; }





		[Column] public string nvPingYinAbbr { get; set; }





		[Column] public DateTime? btBeginDate { get; set; }





		[Column] public DateTime? btEndDate { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? ISSSV { get; set; }





		[Column] public int? vendorflag { get; set; }





		[Column] public string OffLineUserFlag { get; set; }





		[Column] public string CRCFlag { get; set; }





		[Column] public DateTime? LastChangePWDate { get; set; }





		[Column] public string Salt { get; set; }





		[Column] public bool? OnlineFlag { get; set; }





		[Column] public string SapAccount { get; set; }





		[Column] public string SapPassword { get; set; }





		[Column] public int? KeHuID { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string Img { get; set; }





		[Column] public string SSPCSign { get; set; }





		[Column] public string IsEmployee { get; set; }





		[Column] public string CusCode { get; set; }





		[Column] public string CusStamp { get; set; }





		[Column] public string OriginalADName { get; set; }





		[Column] public string Area { get; set; }



	}

    

	[TableName("user_bfp.mstrenyuan_bak20180419")]




	[ExplicitColumns]

    public partial class mstrenyuan_bak20180419 : SSPC_EORDER_DB.Record<mstrenyuan_bak20180419>  
    {



		[Column] public int RenYuanID { get; set; }





		[Column] public string LoginID { get; set; }





		[Column] public string ADName { get; set; }





		[Column] public string LoginPW { get; set; }





		[Column] public int? ShiFouTingYon { get; set; }





		[Column] public string RenYuanBH { get; set; }





		[Column] public string Sap_code { get; set; }





		[Column] public string RenYuanNM { get; set; }





		[Column] public string western_name { get; set; }





		[Column] public int QuYuID { get; set; }





		[Column] public string YiDongDianHua { get; set; }





		[Column] public string Email { get; set; }





		[Column] public string ZhiWu { get; set; }





		[Column] public string Address { get; set; }





		[Column] public int? ShiFouZaiZhi { get; set; }





		[Column] public string BanGongShiChuanZhen { get; set; }





		[Column] public int? SuoShuBuMen { get; set; }





		[Column] public string BeiZhu { get; set; }





		[Column] public int? ErrorTime { get; set; }





		[Column] public int? InitPWD { get; set; }





		[Column] public int? InitDownload { get; set; }





		[Column] public string Mail { get; set; }





		[Column] public string ChengHu { get; set; }





		[Column] public int? ChaKanDengJi { get; set; }





		[Column] public int? IsShenPiRen { get; set; }





		[Column] public int? LevelNO { get; set; }





		[Column] public string mobilePWD { get; set; }





		[Column] public DateTime? mobilePWDCreatedTime { get; set; }





		[Column] public int? UseMPW { get; set; }





		[Column] public int? XUELI { get; set; }





		[Column] public int? ManagerId { get; set; }





		[Column] public int? intZhiWu { get; set; }





		[Column] public int? country { get; set; }





		[Column] public string MD5Password { get; set; }





		[Column] public string nvPingYin { get; set; }





		[Column] public string nvPingYinAbbr { get; set; }





		[Column] public DateTime? btBeginDate { get; set; }





		[Column] public DateTime? btEndDate { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? ISSSV { get; set; }





		[Column] public int? vendorflag { get; set; }





		[Column] public string OffLineUserFlag { get; set; }





		[Column] public string CRCFlag { get; set; }





		[Column] public DateTime? LastChangePWDate { get; set; }





		[Column] public string Salt { get; set; }





		[Column] public bool? OnlineFlag { get; set; }





		[Column] public string SapAccount { get; set; }





		[Column] public string SapPassword { get; set; }





		[Column] public int? KeHuID { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string Img { get; set; }





		[Column] public string SSPCSign { get; set; }





		[Column] public string IsEmployee { get; set; }





		[Column] public string CusCode { get; set; }





		[Column] public string CusStamp { get; set; }





		[Column] public string OriginalADName { get; set; }





		[Column] public string Area { get; set; }



	}

    

	[TableName("user_bfp.mstrenyuan20180601")]




	[ExplicitColumns]

    public partial class mstrenyuan20180601 : SSPC_EORDER_DB.Record<mstrenyuan20180601>  
    {



		[Column] public int RenYuanID { get; set; }





		[Column] public string LoginID { get; set; }





		[Column] public string ADName { get; set; }





		[Column] public string LoginPW { get; set; }





		[Column] public int? ShiFouTingYon { get; set; }





		[Column] public string RenYuanBH { get; set; }





		[Column] public string Sap_code { get; set; }





		[Column] public string RenYuanNM { get; set; }





		[Column] public string western_name { get; set; }





		[Column] public int QuYuID { get; set; }





		[Column] public string YiDongDianHua { get; set; }





		[Column] public string Email { get; set; }





		[Column] public string ZhiWu { get; set; }





		[Column] public string Address { get; set; }





		[Column] public int? ShiFouZaiZhi { get; set; }





		[Column] public string BanGongShiChuanZhen { get; set; }





		[Column] public int? SuoShuBuMen { get; set; }





		[Column] public string BeiZhu { get; set; }





		[Column] public int? ErrorTime { get; set; }





		[Column] public int? InitPWD { get; set; }





		[Column] public int? InitDownload { get; set; }





		[Column] public string Mail { get; set; }





		[Column] public string ChengHu { get; set; }





		[Column] public int? ChaKanDengJi { get; set; }





		[Column] public int? IsShenPiRen { get; set; }





		[Column] public int? LevelNO { get; set; }





		[Column] public string mobilePWD { get; set; }





		[Column] public DateTime? mobilePWDCreatedTime { get; set; }





		[Column] public int? UseMPW { get; set; }





		[Column] public int? XUELI { get; set; }





		[Column] public int? ManagerId { get; set; }





		[Column] public int? intZhiWu { get; set; }





		[Column] public int? country { get; set; }





		[Column] public string MD5Password { get; set; }





		[Column] public string nvPingYin { get; set; }





		[Column] public string nvPingYinAbbr { get; set; }





		[Column] public DateTime? btBeginDate { get; set; }





		[Column] public DateTime? btEndDate { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? ISSSV { get; set; }





		[Column] public int? vendorflag { get; set; }





		[Column] public string OffLineUserFlag { get; set; }





		[Column] public string CRCFlag { get; set; }





		[Column] public DateTime? LastChangePWDate { get; set; }





		[Column] public string Salt { get; set; }





		[Column] public bool? OnlineFlag { get; set; }





		[Column] public string SapAccount { get; set; }





		[Column] public string SapPassword { get; set; }





		[Column] public int? KeHuID { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string Img { get; set; }





		[Column] public string SSPCSign { get; set; }





		[Column] public string IsEmployee { get; set; }





		[Column] public string CusCode { get; set; }





		[Column] public string CusStamp { get; set; }





		[Column] public string OriginalADName { get; set; }





		[Column] public string Area { get; set; }



	}

    

	[TableName("user_bfp.mstrenyuan20180706")]




	[ExplicitColumns]

    public partial class mstrenyuan20180706 : SSPC_EORDER_DB.Record<mstrenyuan20180706>  
    {



		[Column] public int RenYuanID { get; set; }





		[Column] public string LoginID { get; set; }





		[Column] public string ADName { get; set; }





		[Column] public string LoginPW { get; set; }





		[Column] public int? ShiFouTingYon { get; set; }





		[Column] public string RenYuanBH { get; set; }





		[Column] public string Sap_code { get; set; }





		[Column] public string RenYuanNM { get; set; }





		[Column] public string western_name { get; set; }





		[Column] public int QuYuID { get; set; }





		[Column] public string YiDongDianHua { get; set; }





		[Column] public string Email { get; set; }





		[Column] public string ZhiWu { get; set; }





		[Column] public string Address { get; set; }





		[Column] public int? ShiFouZaiZhi { get; set; }





		[Column] public string BanGongShiChuanZhen { get; set; }





		[Column] public int? SuoShuBuMen { get; set; }





		[Column] public string BeiZhu { get; set; }





		[Column] public int? ErrorTime { get; set; }





		[Column] public int? InitPWD { get; set; }





		[Column] public int? InitDownload { get; set; }





		[Column] public string Mail { get; set; }





		[Column] public string ChengHu { get; set; }





		[Column] public int? ChaKanDengJi { get; set; }





		[Column] public int? IsShenPiRen { get; set; }





		[Column] public int? LevelNO { get; set; }





		[Column] public string mobilePWD { get; set; }





		[Column] public DateTime? mobilePWDCreatedTime { get; set; }





		[Column] public int? UseMPW { get; set; }





		[Column] public int? XUELI { get; set; }





		[Column] public int? ManagerId { get; set; }





		[Column] public int? intZhiWu { get; set; }





		[Column] public int? country { get; set; }





		[Column] public string MD5Password { get; set; }





		[Column] public string nvPingYin { get; set; }





		[Column] public string nvPingYinAbbr { get; set; }





		[Column] public DateTime? btBeginDate { get; set; }





		[Column] public DateTime? btEndDate { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? ISSSV { get; set; }





		[Column] public int? vendorflag { get; set; }





		[Column] public string OffLineUserFlag { get; set; }





		[Column] public string CRCFlag { get; set; }





		[Column] public DateTime? LastChangePWDate { get; set; }





		[Column] public string Salt { get; set; }





		[Column] public bool? OnlineFlag { get; set; }





		[Column] public string SapAccount { get; set; }





		[Column] public string SapPassword { get; set; }





		[Column] public int? KeHuID { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string Img { get; set; }





		[Column] public string SSPCSign { get; set; }





		[Column] public string IsEmployee { get; set; }





		[Column] public string CusCode { get; set; }





		[Column] public string CusStamp { get; set; }





		[Column] public string OriginalADName { get; set; }





		[Column] public string Area { get; set; }



	}

    

	[TableName("user_bfp.Sys_RefreshToken")]



	[PrimaryKey("Id", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class Sys_RefreshToken : SSPC_EORDER_DB.Record<Sys_RefreshToken>  
    {



		[Column] public string Id { get; set; }





		[Column] public string Subject { get; set; }





		[Column] public DateTime IssuedUtc { get; set; }





		[Column] public DateTime ExpiresUtc { get; set; }





		[Column] public string ProtectedTicket { get; set; }



	}

    

	[TableName("user_bfp.T_ExcelCustomer")]




	[ExplicitColumns]

    public partial class T_ExcelCustomer : SSPC_EORDER_DB.Record<T_ExcelCustomer>  
    {



		[Column] public int ID { get; set; }





		[Column] public string Name { get; set; }





		[Column] public string ShortName { get; set; }





		[Column] public string CheckName { get; set; }





		[Column] public string _Status { get; set; }





		[Column] public string Area { get; set; }





		[Column] public string Stamp { get; set; }





		[Column] public string CustomerName { get; set; }





		[Column] public string Sign { get; set; }





		[Column] public string Remark { get; set; }



	}

    

	[TableName("user_bfp.tb_MasterDate_History")]




	[ExplicitColumns]

    public partial class tb_MasterDate_History : SSPC_EORDER_DB.Record<tb_MasterDate_History>  
    {



		[Column] public int MasterID { get; set; }





		[Column] public string MasterTable { get; set; }





		[Column] public int lockDataFlag { get; set; }





		[Column] public int Updater { get; set; }





		[Column] public DateTime UpDateTime { get; set; }





		[Column] public DateTime? BeginDate { get; set; }





		[Column] public DateTime? EndDate { get; set; }





		[Column] public string Option { get; set; }





		[Column] public Guid? DoctorID { get; set; }





		[Column] public string Operation { get; set; }





		[Column] public string Remarks { get; set; }



	}

    

	[TableName("user_bfp.tbl_BI_Users_LoginHistory")]




	[ExplicitColumns]

    public partial class tbl_BI_Users_LoginHistory : SSPC_EORDER_DB.Record<tbl_BI_Users_LoginHistory>  
    {



		[Column] public string LoginID { get; set; }





		[Column] public string EmployeeName { get; set; }





		[Column] public DateTime LoginTime { get; set; }





		[Column] public DateTime? LogoutTime { get; set; }





		[Column] public string LoginIP { get; set; }





		[Column] public string CompanyCode { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder")]



	[PrimaryKey("OrderID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder : SSPC_EORDER_DB.Record<tbl_eorder>  
    {



		[Column] public Guid OrderID { get; set; }





		[Column] public string OrderNo { get; set; }





		[Column] public string SAPCode { get; set; }





		[Column] public string SoldToNo { get; set; }





		[Column] public string SoldTo { get; set; }





		[Column] public string RequestType { get; set; }





		[Column] public string VKGRP { get; set; }





		[Column] public string PaymentType { get; set; }





		[Column] public string AccountStatus { get; set; }





		[Column] public string SendTo { get; set; }





		[Column] public string SendToAddress { get; set; }





		[Column] public string SendToPhone { get; set; }





		[Column] public string ShipTo { get; set; }





		[Column] public string ShipToAddress { get; set; }





		[Column] public string ShipToPhone { get; set; }





		[Column] public decimal? Amount { get; set; }





		[Column] public decimal? DisAmount { get; set; }





		[Column] public string CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string UpdateUser { get; set; }





		[Column] public string ReceiptContact { get; set; }





		[Column] public string ReceiptContactPhone { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public DateTime? DeliveryDate { get; set; }





		[Column] public string Reason { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string Approver { get; set; }





		[Column] public DateTime? SubmitTime { get; set; }





		[Column] public string PayTime { get; set; }





		[Column] public string DeliveryType { get; set; }





		[Column] public string City { get; set; }





		[Column] public string DeliveryCity { get; set; }





		[Column] public string OrderName { get; set; }





		[Column] public string DeliveryTerm { get; set; }





		[Column] public string CreditType { get; set; }





		[Column] public string Remark { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_actualamount")]




	[ExplicitColumns]

    public partial class tbl_eorder_actualamount : SSPC_EORDER_DB.Record<tbl_eorder_actualamount>  
    {



		[Column] public string Id { get; set; }





		[Column] public string ApplyNo { get; set; }





		[Column] public string ProductCode { get; set; }





		[Column] public decimal? UseAmount { get; set; }





		[Column] public decimal? ActualAmount { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_bak20171010")]




	[ExplicitColumns]

    public partial class tbl_eorder_bak20171010 : SSPC_EORDER_DB.Record<tbl_eorder_bak20171010>  
    {



		[Column] public Guid OrderID { get; set; }





		[Column] public string OrderNo { get; set; }





		[Column] public string SAPCode { get; set; }





		[Column] public string SoldToNo { get; set; }





		[Column] public string SoldTo { get; set; }





		[Column] public string RequestType { get; set; }





		[Column] public string VKGRP { get; set; }





		[Column] public string PaymentType { get; set; }





		[Column] public string AccountStatus { get; set; }





		[Column] public string SendTo { get; set; }





		[Column] public string SendToAddress { get; set; }





		[Column] public string SendToPhone { get; set; }





		[Column] public string ShipTo { get; set; }





		[Column] public string ShipToAddress { get; set; }





		[Column] public string ShipToPhone { get; set; }





		[Column] public decimal? Amount { get; set; }





		[Column] public decimal? DisAmount { get; set; }





		[Column] public string CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string UpdateUser { get; set; }





		[Column] public string ReceiptContact { get; set; }





		[Column] public string ReceiptContactPhone { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public DateTime? DeliveryDate { get; set; }





		[Column] public string Reason { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string Approver { get; set; }





		[Column] public DateTime? SubmitTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_company")]



	[PrimaryKey("CompanyId", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_company : SSPC_EORDER_DB.Record<tbl_eorder_company>  
    {



		[Column] public Guid CompanyId { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string CompanyName { get; set; }





		[Column] public string Factory { get; set; }





		[Column] public string Icon { get; set; }





		[Column] public string Address { get; set; }





		[Column] public string Bank { get; set; }





		[Column] public string Tax { get; set; }





		[Column] public string Phone { get; set; }





		[Column] public string BigIcon { get; set; }





		[Column] public string SmallIcon { get; set; }





		[Column] public string ShortName { get; set; }





		[Column] public string Stamp { get; set; }





		[Column] public string Sign { get; set; }





		[Column] public int? emcomid { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_cus008")]




	[ExplicitColumns]

    public partial class tbl_eorder_cus008 : SSPC_EORDER_DB.Record<tbl_eorder_cus008>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string ZKHID { get; set; }





		[Column] public string ZEILE { get; set; }





		[Column] public string ZZID { get; set; }





		[Column] public string DESZH { get; set; }





		[Column] public string ZZNMB { get; set; }





		[Column] public string ZVALD { get; set; }





		[Column] public string ZXKFW { get; set; }





		[Column] public string REMARK { get; set; }





		[Column] public string ZDELETE { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_cus009")]




	[ExplicitColumns]

    public partial class tbl_eorder_cus009 : SSPC_EORDER_DB.Record<tbl_eorder_cus009>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string ZKHID { get; set; }





		[Column] public string ZEILE { get; set; }





		[Column] public string ZWTRN { get; set; }





		[Column] public string ZCARD { get; set; }





		[Column] public string ZCVLD { get; set; }





		[Column] public string ZWTPZ { get; set; }





		[Column] public string ZWVLD { get; set; }





		[Column] public string REMARK { get; set; }





		[Column] public string ZDELETE { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_cussales")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_cussale : SSPC_EORDER_DB.Record<tbl_eorder_cussale>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string ZNAME1 { get; set; }





		[Column] public string VTWEG { get; set; }





		[Column] public string SPART { get; set; }





		[Column] public string ZSTREET { get; set; }





		[Column] public string ZADDRESS { get; set; }





		[Column] public string ZPOSTCODE { get; set; }





		[Column] public string ZCITY { get; set; }





		[Column] public string ZTEL { get; set; }





		[Column] public string ZFAX { get; set; }





		[Column] public string VKBUR { get; set; }





		[Column] public string VKGRP { get; set; }





		[Column] public string BZIRK { get; set; }





		[Column] public string ZLXR { get; set; }





		[Column] public string ZLXRDH { get; set; }





		[Column] public string ZTERM { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public string BANKA { get; set; }





		[Column] public string BANKN { get; set; }





		[Column] public string STCEG { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_cussales20180322")]




	[ExplicitColumns]

    public partial class tbl_eorder_cussales20180322 : SSPC_EORDER_DB.Record<tbl_eorder_cussales20180322>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string ZNAME1 { get; set; }





		[Column] public string VTWEG { get; set; }





		[Column] public string SPART { get; set; }





		[Column] public string ZSTREET { get; set; }





		[Column] public string ZADDRESS { get; set; }





		[Column] public string ZPOSTCODE { get; set; }





		[Column] public string ZCITY { get; set; }





		[Column] public string ZTEL { get; set; }





		[Column] public string ZFAX { get; set; }





		[Column] public string VKBUR { get; set; }





		[Column] public string VKGRP { get; set; }





		[Column] public string BZIRK { get; set; }





		[Column] public string ZLXR { get; set; }





		[Column] public string ZLXRDH { get; set; }





		[Column] public string ZTERM { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public string BANKA { get; set; }





		[Column] public string BANKN { get; set; }





		[Column] public string STCEG { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_cussales20180705")]




	[ExplicitColumns]

    public partial class tbl_eorder_cussales20180705 : SSPC_EORDER_DB.Record<tbl_eorder_cussales20180705>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string ZNAME1 { get; set; }





		[Column] public string VTWEG { get; set; }





		[Column] public string SPART { get; set; }





		[Column] public string ZSTREET { get; set; }





		[Column] public string ZADDRESS { get; set; }





		[Column] public string ZPOSTCODE { get; set; }





		[Column] public string ZCITY { get; set; }





		[Column] public string ZTEL { get; set; }





		[Column] public string ZFAX { get; set; }





		[Column] public string VKBUR { get; set; }





		[Column] public string VKGRP { get; set; }





		[Column] public string BZIRK { get; set; }





		[Column] public string ZLXR { get; set; }





		[Column] public string ZLXRDH { get; set; }





		[Column] public string ZTERM { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public string BANKA { get; set; }





		[Column] public string BANKN { get; set; }





		[Column] public string STCEG { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_cusship")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_cusship : SSPC_EORDER_DB.Record<tbl_eorder_cusship>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string VTWEG { get; set; }





		[Column] public string SPART { get; set; }





		[Column] public string PARVW { get; set; }





		[Column] public string KUNN2 { get; set; }





		[Column] public string KUNN2_TXT { get; set; }





		[Column] public string ZADDRESS { get; set; }





		[Column] public string ZLXRDH { get; set; }





		[Column] public string ZLXR { get; set; }





		[Column] public string ZSTREET { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_dispatch")]



	[PrimaryKey("DispatchID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_dispatch : SSPC_EORDER_DB.Record<tbl_eorder_dispatch>  
    {



		[Column] public Guid DispatchID { get; set; }





		[Column] public string ContractNo { get; set; }





		[Column] public string ProductCode { get; set; }





		[Column] public int? ProductAmount { get; set; }





		[Column] public string TrackingNo { get; set; }





		[Column] public string DeviceID { get; set; }





		[Column] public string CarNo { get; set; }





		[Column] public string MasterDriverName { get; set; }





		[Column] public string MaterDriverPhoneNumber { get; set; }





		[Column] public string SlaveDriverName1 { get; set; }





		[Column] public string SlaveDriverPhoneNumber1 { get; set; }





		[Column] public string SlaveDriverName2 { get; set; }





		[Column] public string SlaveDriverPhoneNumber2 { get; set; }





		[Column] public string SlaveDriverName3 { get; set; }





		[Column] public string SlaveDriverPhoneNumber3 { get; set; }





		[Column] public string SlaveDriverName4 { get; set; }





		[Column] public string SlaveDriverPhoneNumber4 { get; set; }





		[Column] public string SlaveDriverName5 { get; set; }





		[Column] public string SlaveDriverPhoneNumber5 { get; set; }





		[Column] public DateTime StartTime { get; set; }





		[Column] public DateTime EndTime { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string RenYuanId { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public string Updater { get; set; }





		[Column] public DateTime UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_dn")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_dn : SSPC_EORDER_DB.Record<tbl_eorder_dn>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string MBLNR { get; set; }





		[Column] public string MJAHR { get; set; }





		[Column] public string ZEILE { get; set; }





		[Column] public string SMBLN { get; set; }





		[Column] public string SMBLP { get; set; }





		[Column] public string BUKRS { get; set; }





		[Column] public string MATNR { get; set; }





		[Column] public string MAKTX { get; set; }





		[Column] public string WERKS { get; set; }





		[Column] public string LGORT { get; set; }





		[Column] public decimal? MENGE { get; set; }





		[Column] public string MEINS { get; set; }





		[Column] public decimal? ERFMG { get; set; }





		[Column] public string ERFME { get; set; }





		[Column] public string CHARG { get; set; }





		[Column] public string VFDAT { get; set; }





		[Column] public string VBELN { get; set; }





		[Column] public string POSNR { get; set; }





		[Column] public DateTime? BLDAT { get; set; }





		[Column] public string LFART { get; set; }





		[Column] public string KUNNR_S { get; set; }





		[Column] public string KUNNR_S_TXT { get; set; }





		[Column] public string KUNNR_C { get; set; }





		[Column] public string KUNNR_C_TXT { get; set; }





		[Column] public string VGBEL { get; set; }





		[Column] public string VGPOS { get; set; }





		[Column] public decimal? NETPR { get; set; }





		[Column] public string WAERS { get; set; }





		[Column] public string VTWEG { get; set; }





		[Column] public string SPART { get; set; }





		[Column] public string VKBUR { get; set; }





		[Column] public string AUART { get; set; }





		[Column] public string BEZEI { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string NAME1 { get; set; }





		[Column] public string VKGRP { get; set; }





		[Column] public string BZIRK { get; set; }





		[Column] public string ZLXR { get; set; }





		[Column] public string ZLXRDH { get; set; }





		[Column] public string ZJHBZ { get; set; }





		[Column] public string ZTDJHDZ { get; set; }





		[Column] public string ZYSLJ { get; set; }





		[Column] public string ROUTE { get; set; }





		[Column] public string ZZTSJ { get; set; }





		[Column] public string ZSONUM { get; set; }





		[Column] public DateTime? CreateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_emailtemplate")]




	[ExplicitColumns]

    public partial class tbl_eorder_emailtemplate : SSPC_EORDER_DB.Record<tbl_eorder_emailtemplate>  
    {



		[Column] public Guid? ID { get; set; }





		[Column] public string Title { get; set; }





		[Column] public string TelContent { get; set; }





		[Column] public string Content { get; set; }





		[Column] public int? Indexes { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string MutiContent { get; set; }





		[Column] public string MutiTel { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_list")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_list : SSPC_EORDER_DB.Record<tbl_eorder_list>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string MATNR { get; set; }





		[Column] public DateTime? DATBI { get; set; }





		[Column] public DateTime? DATAB { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_list_bak")]




	[ExplicitColumns]

    public partial class tbl_eorder_list_bak : SSPC_EORDER_DB.Record<tbl_eorder_list_bak>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string MATNR { get; set; }





		[Column] public DateTime? DATBI { get; set; }





		[Column] public DateTime? DATAB { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_logistics")]




	[ExplicitColumns]

    public partial class tbl_eorder_logistic : SSPC_EORDER_DB.Record<tbl_eorder_logistic>  
    {



		[Column] public Guid? ID { get; set; }





		[Column] public string User { get; set; }





		[Column] public string Email { get; set; }





		[Column] public string Tel { get; set; }





		[Column] public string CompanyCode { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_marm")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_marm : SSPC_EORDER_DB.Record<tbl_eorder_marm>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string WERKS { get; set; }





		[Column] public string MATNR { get; set; }





		[Column] public string MEINH { get; set; }





		[Column] public decimal? UMREZ { get; set; }





		[Column] public decimal? UMREN { get; set; }





		[Column] public string MEINS { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_matnr")]




	[ExplicitColumns]

    public partial class tbl_eorder_matnr : SSPC_EORDER_DB.Record<tbl_eorder_matnr>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string WERKS { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string MATNR { get; set; }





		[Column] public string ZS_NAME { get; set; }





		[Column] public string MEINS { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public string Spec { get; set; }





		[Column] public string SName { get; set; }





		[Column] public string SUnit { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_mvke")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_mvke : SSPC_EORDER_DB.Record<tbl_eorder_mvke>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string VTWEG { get; set; }





		[Column] public string MATNR { get; set; }





		[Column] public string VRKME { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public string SUnit { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_operate")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_operate : SSPC_EORDER_DB.Record<tbl_eorder_operate>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public Guid? OrderID { get; set; }





		[Column] public DateTime? OperateDate { get; set; }





		[Column] public string OperateUser { get; set; }





		[Column] public string OperateType { get; set; }





		[Column] public string OperateRemark { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_page")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_page : SSPC_EORDER_DB.Record<tbl_eorder_page>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string PageName { get; set; }





		[Column] public string PageCode { get; set; }





		[Column] public string ParentPageCode { get; set; }





		[Column] public int Index { get; set; }





		[Column] public string Image { get; set; }





		[Column] public string Html { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string Model { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_pdf1")]




	[ExplicitColumns]

    public partial class tbl_eorder_pdf1 : SSPC_EORDER_DB.Record<tbl_eorder_pdf1>  
    {



		[Column] public Guid? ID { get; set; }





		[Column] public int? RenyuanID { get; set; }





		[Column] public Guid? EorderID { get; set; }





		[Column] public DateTime? CreateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_pdf2")]




	[ExplicitColumns]

    public partial class tbl_eorder_pdf2 : SSPC_EORDER_DB.Record<tbl_eorder_pdf2>  
    {



		[Column] public Guid? ID { get; set; }





		[Column] public int? RenyuanID { get; set; }





		[Column] public Guid? EorderID { get; set; }





		[Column] public DateTime? CreateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_price")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_price : SSPC_EORDER_DB.Record<tbl_eorder_price>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string VTWEG { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string MATNR { get; set; }





		[Column] public DateTime? DATBI { get; set; }





		[Column] public DateTime? DATAB { get; set; }





		[Column] public decimal? KBETR { get; set; }





		[Column] public string KONWA { get; set; }





		[Column] public decimal? KPEIN { get; set; }





		[Column] public string KMEIN { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_price_bak")]




	[ExplicitColumns]

    public partial class tbl_eorder_price_bak : SSPC_EORDER_DB.Record<tbl_eorder_price_bak>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public string VKORG { get; set; }





		[Column] public string VTWEG { get; set; }





		[Column] public string KUNNR { get; set; }





		[Column] public string MATNR { get; set; }





		[Column] public DateTime? DATBI { get; set; }





		[Column] public DateTime? DATAB { get; set; }





		[Column] public decimal? KBETR { get; set; }





		[Column] public string KONWA { get; set; }





		[Column] public decimal? KPEIN { get; set; }





		[Column] public string KMEIN { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_process")]




	[ExplicitColumns]

    public partial class tbl_eorder_process : SSPC_EORDER_DB.Record<tbl_eorder_process>  
    {



		[Column] public Guid? ID { get; set; }





		[Column] public string Process { get; set; }





		[Column] public string CompanyCode { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_product")]



	[PrimaryKey("OrderProductId", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_product : SSPC_EORDER_DB.Record<tbl_eorder_product>  
    {



		[Column] public Guid OrderProductId { get; set; }





		[Column] public Guid? OrderID { get; set; }





		[Column] public string ProductCode { get; set; }





		[Column] public string ProductName { get; set; }





		[Column] public string PaymentType { get; set; }





		[Column] public string SalesUnit { get; set; }





		[Column] public decimal? SalesPrice { get; set; }





		[Column] public decimal? SalesNum { get; set; }





		[Column] public string BaseUnit { get; set; }





		[Column] public int? Convert { get; set; }





		[Column] public decimal? ConvertNum { get; set; }





		[Column] public decimal? VATAmount { get; set; }





		[Column] public string DisRate { get; set; }





		[Column] public decimal? DisAmount { get; set; }





		[Column] public string DisReason { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string DisNo { get; set; }





		[Column] public string DisType { get; set; }





		[Column] public string DisTax { get; set; }





		[Column] public decimal? IsBox { get; set; }





		[Column] public decimal? Rate { get; set; }





		[Column] public string EUnit { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_product_bak")]




	[ExplicitColumns]

    public partial class tbl_eorder_product_bak : SSPC_EORDER_DB.Record<tbl_eorder_product_bak>  
    {



		[Column] public Guid OrderProductId { get; set; }





		[Column] public Guid? OrderID { get; set; }





		[Column] public string ProductCode { get; set; }





		[Column] public string ProductName { get; set; }





		[Column] public string PaymentType { get; set; }





		[Column] public string SalesUnit { get; set; }





		[Column] public decimal? SalesPrice { get; set; }





		[Column] public decimal? SalesNum { get; set; }





		[Column] public string BaseUnit { get; set; }





		[Column] public int? Convert { get; set; }





		[Column] public decimal? ConvertNum { get; set; }





		[Column] public decimal? VATAmount { get; set; }





		[Column] public string DisRate { get; set; }





		[Column] public decimal? DisAmount { get; set; }





		[Column] public string DisReason { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string DisNo { get; set; }





		[Column] public string DisType { get; set; }





		[Column] public string DisTax { get; set; }





		[Column] public decimal? IsBox { get; set; }





		[Column] public decimal? Rate { get; set; }





		[Column] public string EUnit { get; set; }





		[Column] public DateTime? DDate { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_product_type")]




	[ExplicitColumns]

    public partial class tbl_eorder_product_type : SSPC_EORDER_DB.Record<tbl_eorder_product_type>  
    {



		[Column] public Guid? ID { get; set; }





		[Column] public string Matnr { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public int? Type { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_role")]



	[PrimaryKey("RoleID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_role : SSPC_EORDER_DB.Record<tbl_eorder_role>  
    {



		[Column] public Guid RoleID { get; set; }





		[Column] public string RoleName { get; set; }





		[Column] public string RoleCode { get; set; }





		[Column] public string Remark { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_rolepage")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_rolepage : SSPC_EORDER_DB.Record<tbl_eorder_rolepage>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public Guid RoleID { get; set; }





		[Column] public Guid? PageID { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_roleuser")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_roleuser : SSPC_EORDER_DB.Record<tbl_eorder_roleuser>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public Guid RoleID { get; set; }





		[Column] public int? RenYuanID { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_tempsapemail")]




	[ExplicitColumns]

    public partial class tbl_eorder_tempsapemail : SSPC_EORDER_DB.Record<tbl_eorder_tempsapemail>  
    {



		[Column] public Guid? ID { get; set; }





		[Column] public string OrderNo { get; set; }





		[Column] public DateTime? Createtime { get; set; }





		[Column] public decimal? Num { get; set; }





		[Column] public string Unit { get; set; }





		[Column] public string Name { get; set; }





		[Column] public string Mat { get; set; }





		[Column] public string Batch { get; set; }





		[Column] public string ShipNo { get; set; }





		[Column] public string Soldto { get; set; }





		[Column] public string Shipto { get; set; }





		[Column] public string Remark { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_usercustomer")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eorder_usercustomer : SSPC_EORDER_DB.Record<tbl_eorder_usercustomer>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public int? Renyuanid { get; set; }





		[Column] public string CustomerCode { get; set; }





		[Column] public string CompanyCode { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_usercustomer20180322")]




	[ExplicitColumns]

    public partial class tbl_eorder_usercustomer20180322 : SSPC_EORDER_DB.Record<tbl_eorder_usercustomer20180322>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public int? Renyuanid { get; set; }





		[Column] public string CustomerCode { get; set; }





		[Column] public string CompanyCode { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_vgroupdes")]




	[ExplicitColumns]

    public partial class tbl_eorder_vgroupde : SSPC_EORDER_DB.Record<tbl_eorder_vgroupde>  
    {



		[Column] public Guid? ID { get; set; }





		[Column] public string VKGRP { get; set; }





		[Column] public string Description { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }



	}

    

	[TableName("user_bfp.tbl_eorder_workflow")]




	[ExplicitColumns]

    public partial class tbl_eorder_workflow : SSPC_EORDER_DB.Record<tbl_eorder_workflow>  
    {



		[Column] public Guid? ID { get; set; }





		[Column] public Guid? OrderID { get; set; }





		[Column] public int? Renyuanid { get; set; }



	}

    

	[TableName("user_bfp.tbl_eordersub")]



	[PrimaryKey("SubID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eordersub : SSPC_EORDER_DB.Record<tbl_eordersub>  
    {



		[Column] public Guid SubID { get; set; }





		[Column] public Guid OrderID { get; set; }





		[Column] public string SubCode { get; set; }





		[Column] public string CompanyCode { get; set; }





		[Column] public string SapCode { get; set; }





		[Column] public string SapError { get; set; }





		[Column] public int? ISSysc { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }



	}

    

	[TableName("user_bfp.tbl_eordersub_product")]



	[PrimaryKey("SubProductID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_eordersub_product : SSPC_EORDER_DB.Record<tbl_eordersub_product>  
    {



		[Column] public Guid SubProductID { get; set; }





		[Column] public Guid SubID { get; set; }





		[Column] public Guid? OrderProductID { get; set; }





		[Column] public DateTime? CreateTime { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public int? UpdateUser { get; set; }



	}

    

	[TableName("user_bfp.tbl_LanguageResource")]



	[PrimaryKey("CultureCode", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tbl_LanguageResource : SSPC_EORDER_DB.Record<tbl_LanguageResource>  
    {



		[Column] public string CultureCode { get; set; }





		[Column] public string PageID { get; set; }





		[Column] public string ItemID { get; set; }





		[Column] public string ItemContent { get; set; }





		[Column] public int? UpdateUser { get; set; }





		[Column] public DateTime? UpdateTime { get; set; }





		[Column] public string ItemShortContent { get; set; }





		[Column] public int? CreateUser { get; set; }





		[Column] public DateTime? CreateTime { get; set; }



	}

    

	[TableName("user_bfp.tblEOrderAtt")]



	[PrimaryKey("ID", AutoIncrement=false)]


	[ExplicitColumns]

    public partial class tblEOrderAtt : SSPC_EORDER_DB.Record<tblEOrderAtt>  
    {



		[Column] public Guid ID { get; set; }





		[Column] public Guid? OrderID { get; set; }





		[Column] public string Code { get; set; }





		[Column] public string Name { get; set; }





		[Column] public string OldName { get; set; }





		[Column] public string Address { get; set; }





		[Column] public string PdfAddress { get; set; }





		[Column] public decimal? Size { get; set; }





		[Column] public DateTime? Date { get; set; }





		[Column] public string Type { get; set; }





		[Column] public int? UserID { get; set; }



	}

    

	[TableName("user_bfp.Temp_Cus20180402")]



	[PrimaryKey("ID")]




	[ExplicitColumns]

    public partial class Temp_Cus20180402 : SSPC_EORDER_DB.Record<Temp_Cus20180402>  
    {



		[Column] public int ID { get; set; }





		[Column] public string Name { get; set; }





		[Column] public string LName { get; set; }



	}

    

	[TableName("user_bfp.TEMP_CUSTOMER")]




	[ExplicitColumns]

    public partial class TEMP_CUSTOMER : SSPC_EORDER_DB.Record<TEMP_CUSTOMER>  
    {



		[Column] public string KUNNR { get; set; }





		[Column] public string AllName { get; set; }





		[Column] public string LoginName { get; set; }





		[Column] public string LoginID { get; set; }



	}

    

	[TableName("user_bfp.TEMP_CUSTOMER1")]




	[ExplicitColumns]

    public partial class TEMP_CUSTOMER1 : SSPC_EORDER_DB.Record<TEMP_CUSTOMER1>  
    {



		[Column] public string KUNNR { get; set; }





		[Column] public string Name { get; set; }





		[Column] public int? RenyuanID { get; set; }





		[Column] public string LoginID { get; set; }



	}

    

	[TableName("user_bfp.templatecususer")]




	[ExplicitColumns]

    public partial class templatecususer : SSPC_EORDER_DB.Record<templatecususer>  
    {



		[Column] public Guid? ID { get; set; }





		[Column] public string usercode { get; set; }





		[Column] public string cuscode { get; set; }





		[Column] public string companycode { get; set; }





		[Column] public int? userid { get; set; }



	}


}
